kind: pipeline
name: default

steps:
  - name: test
    image: maven:3.6.1-jdk-11-slim
    commands:
      - mvn test

  - name: build
    image: maven:3.6.1-jdk-11-slim
    commands:
      - mvn clean package
      - ls -R

  - name: bake
    image: plugins/docker
    settings:
      username: felherlla
      password: 6jN3MGunnUE6uiT
      repo: felherlla/hello-world
      tags:
        - latest
        - 0.1